In [1]:
import svd_solver as svd
import numpy as np

A = np.array([[5, 2, 3],
              [4, 5, 6],
              [7, 8, 9],])

U, S, Vt, cond_num, A_inv = svd.svd_solver(A)

A_reconst = U @ S @ Vt

npU, npS, npV = np.linalg.svd(A)

npA_recon = npU @ np.diag(npS) @ npV

# Print the matrices for comparison
print("Custom U:")
print(U)

print("\nNumPy U:")
print(npU)

# Compare V matrices
print("\nCustom Vt")
print(Vt)

print("\nNumPy Vt")
print(npV)

# Compare Sigma matrices
print("\nCustom S (Sigma):")
print(S)

print("\nNumPy S (Sigma):")
print(npS)

# Compare the reconstructed matrix A
print("\nCustom Reconstructed Matrix (U @ S @ Vt):")
print(A_reconst)

print("\nNumpy Matrix A reconstructed")
print(npA_recon)

Custom U:
[[ 0.32717864  0.93556421 -0.13294265]
 [ 0.50256733 -0.29141461 -0.81394324]
 [ 0.8002376  -0.19949221  0.56552864]]

NumPy U:
[[-0.32717864  0.93556421 -0.13294265]
 [-0.50256733 -0.29141461 -0.81394324]
 [-0.8002376  -0.19949221  0.56552864]]

Custom Vt
[[ 0.5317045   0.55017589  0.64389193]
 [ 0.83522779 -0.46657511 -0.29103642]
 [ 0.14030273  0.69254181 -0.70760228]]

NumPy Vt
[[-0.5317045  -0.55017589 -0.64389193]
 [ 0.83522779 -0.46657511 -0.29103642]
 [ 0.14030273  0.69254181 -0.70760228]]

Custom S (Sigma):
[[17.39279188  0.          0.        ]
 [ 0.          2.53310192  0.        ]
 [ 0.          0.          0.27237001]]

NumPy S (Sigma):
[17.39279188  2.53310192  0.27237001]

Custom Reconstructed Matrix (U @ S @ Vt):
[[5. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Numpy Matrix A reconstructed
[[5. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Clearly not every single value of every matrix lines up between my custom solver and Numpy's version, however, they both reconstruct the desired Matrix appropriately.

In [8]:

print("Custom SVD solver condition number and inverse matrix:")
print(cond_num)
print(A_inv)


print("Numpy condition number and inverse matrix:")
print(np.linalg.cond(A))
print(np.linalg.inv(A))

Custom SVD solver condition number and inverse matrix:
63.85722159418202
[[ 0.25       -0.5         0.25      ]
 [-0.5        -2.          1.5       ]
 [ 0.25        2.16666667 -1.41666667]]
Numpy condition number and inverse matrix:
63.85722159418491
[[ 0.25       -0.5         0.25      ]
 [-0.5        -2.          1.5       ]
 [ 0.25        2.16666667 -1.41666667]]


As we can see the condition numbers and inverse matrices are also pretty much the exact same. There is only a minor difference in the condition number due to floating point imprecision